INSERT INTO burgers (name, devoured) VALUES ("Astro Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("Astro Cheeseburger", false);
INSERT INTO burgers (name, devoured) VALUES ("Mars Chili Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("Titan Astro Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("Titan Cheeseburger", false);
INSERT INTO burgers (name, devoured) VALUES ("Titan Mars Chili Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("Dagobah Avocado Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("Titan Dagobah Avocado Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("Dagobah Avocado Cheeseburger", false);
INSERT INTO burgers (name, devoured) VALUES ("Titan Dagobah Avocado Cheeseburger", false);
INSERT INTO burgers (name, devoured) VALUES ("Mercury Melt", false);
INSERT INTO burgers (name, devoured) VALUES ("Venus Garden Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("Pluto Bacon Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("Pluto Bacon Cheeseburger", false);
INSERT INTO burgers (name, devoured) VALUES ("Titan Pluto Bacon Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("Titan Pluto Bacon Cheeseburger", false);
INSERT INTO burgers (name, devoured) VALUES ("MilkyWay Burger", false);
INSERT INTO burgers (name, devoured) VALUES ("MilkyWay Cheeseburger", false);
INSERT INTO burgers (name, devoured) VALUES ("Titan MilkyWay Burger ", false);
INSERT INTO burgers (name, devoured) VALUES ("Titan MilkyWay Cheeseburger", false);